export interface TrainingCampModule {
  id: string;
  sourceChapter: number;
  title: string;
  leetcodeProblemIds?: string[];
  items: string[];
}

export interface TrainingCampPhase {
  id: string;
  order: number;
  title: string;
  description: string;
  modules: TrainingCampModule[];
}

export const kTrainingCampPhases: TrainingCampPhase[] = [
  {
    id: 'foundation',
    order: 1,
    title: '入門營',
    description: '從 C++ 語法、基礎資料結構，到樹、圖、貪心、分治、高精度、搜尋與動態規劃入門。',
    modules: [
      {
        id: 'foundation-cpp-basics',
        sourceChapter: 1,
        title: 'C++ 基礎知識',
        leetcodeProblemIds: [
          'tp-lc-167',
          'math-lc-204',
          'tp-001',
          'math-lc-1922',
          'lc-1480',
          'lc-1929',
          'lc-1672',
          'lc-1108',
          'lc-2011',
          'lc-26'
        ],
        items: [
          '開啟算法之旅',
          '常用的數據類型',
          '玩轉輸入和輸出',
          '常用的運算符',
          '選擇結構語句',
          'if 條件語句',
          'switch 條件語句',
          '循環結構語句',
          'for 語句',
          'while 語句',
          'do while 語句',
          '巧用數組',
          '一維數組',
          '二維數組',
          '玩轉字符串',
          'C 風格的字符串',
          'C++ string 類型的字符串',
          '結構體的應用',
          '指針的應用'
        ]
      },
      {
        id: 'foundation-algorithm-beauty',
        sourceChapter: 2,
        title: '算法之美',
        leetcodeProblemIds: [
          'math-lc-372',
          'dp-lc-516',
          'lc-762',
          'lc0x3f-931',
          'math-lc-50',
          'lc-1137',
          'lc0x3f-70',
          'lc-3304',
          'treedp-lc-543'
        ],
        items: [
          '算法複雜度',
          '時間複雜度',
          '空間複雜度',
          '函數',
          '標準函數',
          '傳值參數',
          '引用參數',
          '數組參數',
          '遞歸',
          '遞歸函數',
          '遞歸的原理'
        ]
      },
      {
        id: 'foundation-linear-list',
        sourceChapter: 3,
        title: '線性表的應用',
        leetcodeProblemIds: [
          'lc-725',
          'mono-001',
          'lc-817',
          'lc0x3f-1019',
          'lc-206',
          'lc-21',
          'lc-25',
          'lc-1441',
          'lc-232',
          'lc-641'
        ],
        items: [
          '順序表',
          '插入',
          '刪除',
          '鏈表',
          '單鏈表',
          '雙向鏈表',
          '循環鏈表',
          '靜態鏈表',
          '棧',
          '入棧',
          '出棧',
          '取棧頂元素',
          '隊列',
          '順序隊列',
          '循環隊列',
          'STL 中的常用函數和容器',
          'sort()',
          'vector（向量）',
          '訓練：角谷猜想',
          'stack（棧）',
          '訓練：數字遊戲',
          'queue（隊列）',
          '訓練：騎士移動',
          'list（雙向鏈表）',
          '訓練：新兵隊列訓練'
        ]
      },
      {
        id: 'foundation-tree',
        sourceChapter: 4,
        title: '樹的應用',
        leetcodeProblemIds: [
          'lc-404',
          'lc-671',
          'lc-872',
          'lc-1214-2',
          'lc-144',
          'lc-94',
          'lc-145',
          'lc-102',
          'lc-105',
          'lc-98',
          'lc-450'
        ],
        items: [
          '樹',
          '樹的存儲',
          '樹、森林與二叉樹的轉換',
          '二叉樹',
          '二叉樹的性質',
          '滿二叉樹和完全二叉樹',
          '二叉樹的存儲結構',
          '二叉樹遍歷',
          '先序遍歷',
          '中序遍歷',
          '後序遍歷',
          '層次遍歷',
          '訓練1：新二叉樹',
          '訓練2：二叉樹遍歷',
          '哈夫曼樹',
          '哈夫曼編碼',
          '哈夫曼編碼的長度計算方法',
          '訓練1：圍欄修復',
          '訓練2：信息熵',
          '二叉搜索樹',
          '二叉搜索樹原理詳解',
          '查找',
          '插入',
          '創建',
          '刪除',
          '訓練1：落葉',
          '訓練2：完全二叉搜索樹'
        ]
      },
      {
        id: 'foundation-graph',
        sourceChapter: 5,
        title: '圖論基礎',
        leetcodeProblemIds: [
          'graph-lc-542',
          'graph-lc-1162',
          'lc-lcp-07',
          'lc-1548',
          'graph-lc-200',
          'graph-001',
          'lc-841',
          'graph-002',
          'lc-1091',
          'lc-785'
        ],
        items: [
          '圖的存儲',
          '鄰接矩陣',
          '邊集數組',
          '鄰接表',
          '鏈式前向星',
          '圖的存儲技巧',
          '圖的遍歷',
          '廣度優先遍歷',
          '深度優先遍歷',
          '訓練1：最大的節點',
          '訓練2：油田'
        ]
      },
      {
        id: 'foundation-algorithm-intro',
        sourceChapter: 6,
        title: '基礎算法與技巧',
        leetcodeProblemIds: [
          'lc0x3f-1144',
          'int-001',
          'lc0x3f-1247',
          'heap-001',
          'lc-455',
          'int-lc-435',
          'heap-lc-215',
          'lc-912-2',
          'lc-973',
          'bs-lc-410'
        ],
        items: [
          '貪心算法',
          '貪心算法秘籍',
          '最優裝載問題',
          '訓練1：部分背包問題',
          '訓練2：排隊接水',
          '訓練3：線段覆蓋',
          '分治算法',
          '分治算法秘籍',
          '合併排序',
          '快速排序',
          '訓練1：排序（模板）',
          '訓練2：求第 k 小的數',
          '常用陣列與區間技巧',
          '前綴和與二維前綴和',
          '差分與二維差分',
          '雙指針與滑動窗口',
          '雙指針算法 (同向與對向)',
          '滑動窗口基礎'
        ]
      },
      {
        id: 'foundation-basic-math',
        sourceChapter: 7,
        title: '基礎數論與數學入門',
        items: [
          '位運算技巧',
          '常用位運算操作與奇偶判斷',
          'x & (x-1) 的巧妙應用',
          '質數與篩法',
          '質數判定與分解',
          '埃氏篩與歐拉線性篩',
          '最大公約數與最小公倍數',
          '歐幾里得算法 (輾轉相除法)',
          '快速冪',
          '取模運算律',
          '整數快速冪算法'
        ]
      },
      {
        id: 'foundation-big-integer',
        sourceChapter: 8,
        title: '高精度計算',
        leetcodeProblemIds: [
          'lc-2614',
          'lc-3115',
          'lc-3556',
          'lc-3765',
          'lc-989',
          'lc-2',
          'lc-2816',
          'math-lc-50',
          'lc-166'
        ],
        items: [
          '高精度加法',
          '接收和存儲數據',
          '處理進制',
          '訓練：A+B Problem',
          '高精度減法',
          '比較大小',
          '接收和存儲數據',
          '處理借位',
          '訓練：A-B Problem',
          '高精度乘法',
          '接收和存儲數據',
          '處理進制',
          '訓練：A*B Problem',
          '高精度除法',
          '接收和存儲數據',
          '按位相除',
          '訓練：A/B Problem'
        ]
      },
      {
        id: 'foundation-search',
        sourceChapter: 9,
        title: '搜索算法入門',
        leetcodeProblemIds: [
          'bs-lc-34',
          'lc-261',
          'bs-lc-153',
          'lc-323',
          'bs-lc-704',
          'bs-001',
          'lc-875',
          'bs-lc-410',
          'lc-46',
          'lc-51-2',
          'lc-1091',
          'lc-1293'
        ],
        items: [
          '二分算法',
          '二分查找',
          '二分答案',
          '訓練1：查找',
          '訓練2：跳石頭遊戲',
          '訓練3：花環',
          '深度優先搜索',
          '回溯法的原理',
          '回溯法模板',
          '訓練1：01 背包問題',
          '訓練2：圖的 m 著色問題',
          '訓練3：n 皇后問題',
          '廣度優先搜索',
          '分支限界法的原理',
          '分支限界法秘籍',
          '訓練1：迷宮問題',
          '訓練2：01 背包問題'
        ]
      },
      {
        id: 'foundation-dp',
        sourceChapter: 10,
        title: '動態規劃入門',
        leetcodeProblemIds: [
          'lc0x3f-1227',
          'lc0x3f-1884',
          'lc-1221',
          'lc-2294',
          'lc0x3f-70',
          'lc0x3f-746',
          'dp-lc-322',
          'lc-474',
          'dp-lc-1143',
          'dp-002',
          'lc-53',
          'lc-1547',
          'lc-1039'
        ],
        items: [
          '動態規劃秘籍',
          '動態規劃的三個要素',
          '動態規劃的設計方法',
          '背包問題',
          '01 背包問題',
          '完全背包問題',
          '訓練1：骨頭收藏家',
          '訓練2：存錢罐',
          '線性動態規劃',
          '訓練1：超級樓梯',
          '訓練2：數字三角形',
          '訓練3：最長上升子序列',
          '訓練4：最長公共子序列',
          '訓練5：最大連續子段和',
          '區間動態規劃',
          '訓練1：迴文',
          '訓練2：括號匹配',
          '訓練3：乘法難題',
          '訓練4：猴子派對'
        ]
      }
    ]
  },
  {
    id: 'strengthening',
    order: 2,
    title: '提升營',
    description: '補齊 STL、實用資料結構、查找與字串、平衡樹、圖論提高、搜尋提高與 DP 提升。',
    modules: [
      {
        id: 'strengthening-stl',
        sourceChapter: 1,
        title: 'STL',
        leetcodeProblemIds: [
          'heap-lc-23',
          'heap-lc-295',
          'int-lc-218',
          'heap-003',
          'lc-641',
          'lc0x3f-2558',
          'lc-703',
          'lc-2166',
          'lc-2215',
          'lc-692',
          'lc0x3f-373',
          'lc-146'
        ],
        items: [
          'deque（雙端隊列）',
          '訓練：度熊學隊列',
          'priority_queue（優先隊列）',
          '訓練1：第 k 大的數',
          '訓練2：表演評分',
          'bitset（位圖）',
          '定義與初始化',
          '基本操作',
          '訓練：集合運算',
          'set、multiset（集合、多重集合）',
          '訓練1：集合合併',
          '訓練2：並行處理',
          'map、multimap（映射、多重映射）',
          '訓練1：硬木種類',
          '訓練2：水果',
          'STL 中的常用函數',
          'fill()',
          'nth_element()',
          'lower_bound()、upper_bound()',
          'next_permutation()、prev_permutation()',
          '訓練1：中位數',
          '訓練2：字謎'
        ]
      },
      {
        id: 'strengthening-practical-data-structures',
        sourceChapter: 2,
        title: '實用的資料結構',
        leetcodeProblemIds: [
          'dsu-004',
          'seg-002',
          'lift-001',
          'dsu-lc-1579',
          'dsu-001',
          'dsu-003',
          'lc-1101',
          'lc-235',
          'lc-236',
          'seg-001',
          'lc-308',
          'lc-715',
          'mono-003'
        ],
        items: [
          '並查集',
          '訓練1：暢通工程',
          '訓練2：方塊棧',
          '倍增、稀疏表（ST）、區間值查詢（RMQ）',
          '倍增',
          '稀疏表',
          '區間值查詢',
          '訓練1：區間值差',
          '訓練2：頻繁值',
          '最近公共祖先（LCA）',
          '暴力搜索法',
          '樹上倍增法',
          '線上區間值查詢算法',
          '離線 Tarjan 算法',
          '訓練1：最近公共祖先',
          '訓練2：樹上距離',
          '樹狀數組',
          '一維樹狀數組',
          '多維樹狀數組',
          '訓練1：數星星',
          '訓練2：矩形區域查詢',
          '線段樹',
          '基本操作',
          '懶操作',
          '訓練1：敵兵布陣',
          '訓練2：簡單的整數問題'
        ]
      },
      {
        id: 'strengthening-searching',
        sourceChapter: 3,
        title: '查找算法',
        leetcodeProblemIds: [
          'str-lc-208',
          'str-lc-214',
          'str-lc-1392',
          'str-lc-3008',
          'lc-1',
          'str-lc-28',
          'lc-1408',
          'lc-211',
          'lc-212',
          'lc-1032',
          'lc0x3f-421',
          'lc-49'
        ],
        items: [
          '散列表',
          '雜湊函數',
          '開放地址法',
          '鏈結位址法',
          '建立公共溢位區',
          '散列查找及其性能分析',
          '訓練：雪花',
          '字串模式比對 (BF與KMP)',
          'BF 算法',
          'KMP 算法',
          '訓練1：統計字數',
          '訓練2：字串匹配',
          '字典樹（Trie 樹）',
          '創建',
          '查找',
          '應用',
          '訓練：單字翻譯',
          '字符串哈希 (String Hashing)',
          'Rabin-Karp 演算法',
          '雙重哈希防碰撞技巧',
          'Manacher 演算法 (馬拉車)',
          'O(n) 求解最長回文子串'
        ]
      },
      {
        id: 'strengthening-balanced-trees',
        sourceChapter: 4,
        title: '平衡樹',
        leetcodeProblemIds: [
          'seg-003',
          'lc-1469',
          'int-003',
          'lc-2764',
          'lc-1382',
          'lc-98',
          'lc-450',
          'lc-729',
          'lc-731',
          'lc-715',
          'lc-1206',
          'lc-146'
        ],
        items: [
          '樹高與性能',
          '平衡二叉搜索樹（AVL 樹）',
          '調整平衡的方法',
          '插入',
          '創建',
          '刪除',
          '訓練：雙重隊列',
          '樹堆（Treap）',
          '右旋和左旋',
          '插入',
          '刪除',
          '前驅',
          '後繼',
          '訓練：少林功夫',
          '伸展樹（Splay 樹）',
          '時空局部性的原理',
          '右旋和左旋',
          '伸展',
          '查找',
          '插入',
          '分裂',
          '合併',
          '刪除',
          '區間操作',
          '算法分析',
          '訓練1：玩鍊子',
          '訓練2：強記憶'
        ]
      },
      {
        id: 'strengthening-graph-advanced',
        sourceChapter: 5,
        title: '圖論提高',
        leetcodeProblemIds: [
          'graph-lc-827',
          'graph-lc-1345',
          'lc0x3f-1976',
          'lc0x3f-1254',
          'lc-1192',
          'graph-004',
          'lc-1568',
          'graph-lc-207',
          'graph-lc-210',
          'lc-785',
          'lc-886'
        ],
        items: [
          '連通圖與強連通圖',
          '橋與割點',
          '雙連通分量的縮點',
          'Tarjan 算法',
          '無向圖的橋',
          '無向圖的割點',
          '有向圖的強連通分量',
          '訓練1：道路建設',
          '訓練2：校園網絡',
          '歐拉路徑與歐拉迴路',
          '七橋問題與存在性判定',
          'Hierholzer 演算法',
          '二分圖基礎',
          '二分圖染色判定',
          '2-SAT 問題',
          '邏輯滿足性與強連通分量的結合'
        ]
      },
      {
        id: 'strengthening-graph-algorithms',
        sourceChapter: 6,
        title: '圖論算法',
        leetcodeProblemIds: [
          'graph-003',
          'mst-lc-1168',
          'sp-lc-2642',
          'lc-3219',
          'mst-lc-1584',
          'lc-1135',
          'sp-lc-743',
          'sp-lc-1514',
          'sp-lc-1334',
          'sp-lc-787',
          'graph-lc-210',
          'graph-004'
        ],
        items: [
          '最小生成樹 (Prim, Kruskal)',
          'Prim 算法',
          'Kruskal 算法',
          '訓練1：叢林之路',
          '訓練2：聯網',
          '最短路徑 (Dijkstra, Floyd, Bellman-Ford, SPFA)',
          'Dijkstra 算法',
          'Floyd 算法',
          'Bellman-Ford 算法',
          'SPFA 算法',
          '訓練1：重型運輸',
          '訓練2：貨幣兌換',
          '訓練3：蟲洞',
          '拓撲排序',
          '訓練1：家族樹',
          '訓練2：標籤球',
          '關鍵路徑',
          '訓練1：指令安排',
          '訓練2：家務瑣事'
        ]
      },
      {
        id: 'strengthening-search-advanced',
        sourceChapter: 7,
        title: '搜尋算法提高',
        leetcodeProblemIds: [
          'graph-lc-2608',
          'lc0x3f-1210',
          'lc0x3f-924',
          'lc-1786',
          'lc-37',
          'lc-1263',
          'lc-752',
          'lc-773',
          'lc-854',
          'graph-005',
          'bm-lc-847',
          'lc-1293'
        ],
        items: [
          '剪枝優化',
          '訓練1：數獨遊戲',
          '訓練2：小木棍',
          '嵌套廣度優先搜尋',
          '訓練：推箱子',
          '雙向廣度優先搜尋',
          '訓練：魔鬼 II',
          '啟發式搜尋 (A*, IDA*)',
          'A* 算法',
          'IDA* 算法',
          '訓練1：八數碼問題',
          '訓練2：第 k 短路徑'
        ]
      },
      {
        id: 'strengthening-dp',
        sourceChapter: 8,
        title: '動態規劃提升',
        leetcodeProblemIds: [
          'treedp-lc-124',
          'bm-lc-698',
          'treedp-lc-968',
          'bm-lc-1239',
          'treedp-lc-337',
          'treedp-lc-543',
          'treedp-lc-834',
          'bm-lc-847',
          'lc-943',
          'mono-003',
          'lc-1438',
          'dp-002',
          'lc-2463'
        ],
        items: [
          '樹狀動態規劃',
          '訓練1：戰略遊戲',
          '訓練2：工人請願書',
          '狀態壓縮動態規劃',
          '訓練1：旅行商問題',
          '訓練2：玉米田',
          '動態規劃優化 (倍增、資料結構、單調隊列)',
          '倍增優化',
          '資料結構優化',
          '單調隊列優化',
          '訓練1：最長公共上升子序列',
          '訓練2：滑動視窗'
        ]
      },
      {
        id: 'strengthening-advanced-math',
        sourceChapter: 9,
        title: '進階數論與博弈論',
        items: [
          '同餘與逆元',
          '擴展歐幾里得演算法 (ExGCD)',
          '乘法逆元 (費馬小定理與ExGCD求法)',
          '中國剩餘定理 (CRT)',
          '組合數學',
          '排列組合計算',
          'Lucas 定理',
          '矩陣快速冪',
          '矩陣乘法基礎',
          '利用矩陣快速冪優化 DP 轉移',
          '博弈論基礎',
          'Nim 遊戲',
          'SG 函數與 Sprague-Grundy 定理'
        ]
      }
    ]
  },
  {
    id: 'advanced',
    order: 3,
    title: '進階營',
    description: '聚焦進階資料結構、字串算法、樹上操作、網路流與複雜動態規劃優化。',
    modules: [
      {
        id: 'advanced-data-structures',
        sourceChapter: 1,
        title: '數據結構進階',
        leetcodeProblemIds: [
          'mono-002',
          'seg-005',
          'mono-004',
          'seg-004',
          'lc-1206',
          'lc-715',
          'lc-729',
          'lc-731',
          'seg-001',
          'lc-308',
          'lc-3515',
          'lc-1409',
          'lc-lcr-170'
        ],
        items: [
          '分塊算法',
          '預處理',
          '區間更新',
          '區間查詢',
          '訓練1：超級馬裏奧',
          '訓練2：序列操作',
          '跳躍表',
          '跳躍表的結構體定義',
          '查找',
          '插入',
          '刪除',
          '訓練1：第 k 大的數',
          '訓練2：鬱悶的出納員',
          '莫隊算法 (Mo\'s Algorithm)',
          '基礎莫隊',
          '帶修莫隊',
          '回滾莫隊',
          'CDQ 分治',
          '處理多維偏序問題 (三維偏序)'
        ]
      },
      {
        id: 'advanced-string-algorithms',
        sourceChapter: 2,
        title: '字符串算法進階',
        leetcodeProblemIds: [
          'lc0x3f-1803',
          'lc-1948',
          'lc-3045',
          'lc-3093',
          'lc-212',
          'lc-1032',
          'lc-2223',
          'str-lc-1044',
          'lc-30',
          'lc-1707',
          'lc-1392'
        ],
        items: [
          'AC 自動機',
          '創建字典樹',
          '創建 AC 自動機',
          '模式匹配',
          '訓練1：病毒侵襲',
          '訓練2：DNA 序列',
          '後綴數組 (SA)',
          '基數排序',
          '後綴數組詳解',
          '後綴數組的應用',
          '訓練1：牛奶模式',
          '訓練2：音樂主題',
          '後綴自動機 (SAM)',
          'SAM的狀態與轉移',
          'SAM的構建與應用',
          '回文樹 / 回文自動機 (PAM)',
          'PAM的結構與構建算法'
        ]
      },
      {
        id: 'advanced-tree-operations',
        sourceChapter: 3,
        title: '樹上操作',
        leetcodeProblemIds: [
          'lift-lc-2458',
          'lc0x3f-1617',
          'lift-lc-2846',
          'lc0x3f-2003',
          'lc-235',
          'lc-236',
          'lc-2277',
          'treedp-lc-834',
          'lc-3515-2',
          'lc-1123',
          'lc-1483'
        ],
        items: [
          '樹鏈剖分',
          '預處理',
          '求解最近公共祖先',
          '樹鏈剖分與線段樹',
          '訓練1：樹上距離',
          '訓練2：樹上操作',
          '點分治',
          '樹的重心',
          '重心分解',
          '訓練1：樹上兩個節點之間的路徑數',
          '訓練2：遊船之旅',
          '邊分治',
          '重建樹',
          '求解中心邊',
          '中心邊分解',
          '訓練1：樹上查詢',
          '訓練2：樹上兩個節點之間的路徑數'
        ]
      },
      {
        id: 'advanced-complex-trees',
        sourceChapter: 4,
        title: '複雜樹',
        leetcodeProblemIds: [
          'seg-lc-2286',
          'heap-lc-1675',
          'lc-2250',
          'dsu-lc-1697',
          'lc-973',
          'lc0x3f-373',
          'lc-703',
          'lc-715',
          'lc-731',
          'lc-3515',
          'lc-1206'
        ],
        items: [
          'KD 樹',
          '創建 KD 樹',
          '搜索 m 近鄰',
          '訓練1：最近的取款機',
          '訓練2：最近鄰 m 點',
          '左偏樹',
          '左偏樹的性質',
          '基本操作',
          '訓練1：猴王',
          '訓練2：小根堆',
          '動態樹 (LCT)',
          'LCT 的性質',
          'LCT 的基本操作',
          '訓練1：動態樹的異或和',
          '訓練2：動態樹的最值',
          '樹套樹',
          '線段樹套平衡樹',
          '線段樹套線段樹',
          '訓練1：動態區間問題',
          '訓練2：打馬賽克'
        ]
      },
      {
        id: 'advanced-persistent-data-structures',
        sourceChapter: 5,
        title: '可持久化數據結構',
        leetcodeProblemIds: [
          'lc-3027-2',
          'lc-3072',
          'lc-3624',
          'lc-3187',
          'lc0x3f-421',
          'lc-1707',
          'lc-2479',
          'seg-001',
          'lc-715',
          'lc-729',
          'lc-lcr-170'
        ],
        items: [
          '可持久化線段樹 (主席樹)',
          '訓練1：超級馬裏奧',
          '訓練2：記憶重現',
          '可持久化字典樹',
          '訓練：最大異或和'
        ]
      },
      {
        id: 'advanced-graph-algorithms',
        sourceChapter: 6,
        title: '圖論算法進階',
        leetcodeProblemIds: [
          'lc0x3f-1782',
          'sp-lc-2699',
          'lc0x3f-2127',
          'lc0x3f-882',
          'lc-1820',
          'lc-2123',
          'lc-3385',
          'lc-lcp-04',
          'lc-1947',
          'lc-785',
          'lc-886',
          'lc-2403'
        ],
        items: [
          'EK 算法',
          '訓練：排水系統',
          'Dinic 算法',
          '訓練：電力網絡',
          'ISAP 算法',
          '訓練：美味佳餚',
          '二分圖匹配 (最大匹配、匈牙利算法)',
          '最大匹配算法',
          '匈牙利算法',
          '訓練1：完美的牛棚',
          '訓練2：逃脫',
          '最大流最小割',
          '訓練1：最小邊割集',
          '訓練2：最小點割集',
          '訓練3：最大收益',
          '最小費用最大流',
          '訓練1：農場之旅',
          '訓練2：航空路線',
          '二分圖最大權匹配',
          'KM 算法 (Kuhn-Munkres 算法)',
          '有向圖的最小生成樹',
          '朱劉算法 (Chu-Liu / Edmonds 算法)'
        ]
      },
      {
        id: 'advanced-dp',
        sourceChapter: 7,
        title: '動態規劃進階',
        leetcodeProblemIds: [
          'dp-004',
          'lc-3562',
          'dp-lc-1312',
          'lc-2246',
          'dp-003',
          'lc-474',
          'lc-494',
          'dp-lc-322',
          'lc-879',
          'treedp-lc-337',
          'treedp-lc-834',
          'lc-2463',
          'lc-337'
        ],
        items: [
          '背包問題進階 (多重、分組、混合)',
          '多重背包問題',
          '訓練：硬幣',
          '分組背包問題',
          '訓練：價值最大化',
          '混合背包問題',
          '訓練：最少硬幣',
          '樹形 DP 進階 (背包類、不定根)',
          '背包類樹形 DP',
          '訓練1：城堡中的寶物',
          '訓練2：蘋果樹',
          '不定根樹形 DP',
          '訓練1：最大累積度',
          '訓練2：最遠距離'
        ]
      },
      {
        id: 'advanced-complex-dp',
        sourceChapter: 8,
        title: '複雜動態規劃及其優化',
        leetcodeProblemIds: [
          'lift-005',
          'dp-005',
          'bm-lc-1799',
          'dp-lc-2707',
          'lc-3677',
          'lc-3448',
          'lc-2184',
          'lc-1931',
          'lc-1659',
          'lc-3500',
          'lc-3826',
          'lc-1547',
          'lc-1039'
        ],
        items: [
          '數位 DP',
          '訓練1：不吉利的數字',
          '訓練2：定時炸彈',
          '插頭 DP',
          '訓練1：鋪磚',
          '訓練2：多迴路連通性問題',
          '斜率優化',
          '訓練1：打印文章',
          '訓練2：批處理作業',
          '四邊形不等式優化',
          '訓練：劃分'
        ]
      },
      {
        id: 'advanced-math',
        sourceChapter: 9,
        title: '高級數論與多項式算法',
        items: [
          '多項式運算',
          '快速傅里葉變換 (FFT)',
          '快速數論變換 (NTT)',
          '莫比烏斯反演 (Möbius Inversion)',
          '數論函數與狄利克雷卷積',
          '反演公式與應用',
          '亞線性篩法',
          '杜教篩'
        ]
      }
    ]
  }
];

export function isTrainingItem(item: string) {
  return item.startsWith('訓練');
}

export function getTrainingCampStats(phases: TrainingCampPhase[] = kTrainingCampPhases) {
  const modules = phases.flatMap((phase) => phase.modules);
  const itemCount = modules.reduce((total, module) => total + module.items.length, 0);
  const trainingCount = modules.reduce(
    (total, module) => total + module.items.filter(isTrainingItem).length,
    0
  );
  const leetcodeProblemCount = new Set(modules.flatMap((module) => module.leetcodeProblemIds ?? [])).size;

  return {
    phaseCount: phases.length,
    moduleCount: modules.length,
    itemCount,
    trainingCount,
    leetcodeProblemCount
  };
}
